closes #19
Kaichou-Project/kaichou-graduation pull request #45
Opened 2021-06-19 02:24 UTC by Austinx88

Added a message card function that takes title, message, and author and outputs it like this.
Not finalized  some issues there, just a base of what I have that works atm. 
![image](https://user-images.githubusercontent.com/44851962/122628332-85dbcd80-d083-11eb-9b28-9501a1359165.png)

2021-06-19 11:31 UTC, RedMaps commented
Just saying, you might wanna merge main into this soon, looks like its way behind rn ^^

2021-06-20 02:40 UTC, Austinx88 commented
Will do thanks for the feedback

2021-06-22 00:50 UTC, Austinx88 commented
Will push from my main branch after this figuring things out.

2021-06-23 03:01 UTC, Austinx88 commented
Here it looks like so far:
![image](https://user-images.githubusercontent.com/44851962/123028653-b6867480-d3ad-11eb-84b8-e713c063eea6.png)
Ignore the deleting of variable file as I thought it would delete it from commit not in total.

2021-06-23 04:03 UTC, RedMaps commented
This seems to have multiple build errors right now. I get this when i start dev: 
![image](https://user-images.githubusercontent.com/16868419/123033746-890aec80-d3e8-11eb-886c-e5ba52746750.png)
Also just from the pictures the spacing of the text seems to be off quite a bit as well as the thing at the top right being a bit too big.

2021-06-23 19:23 UTC, Austinx88 commented
Sorry about that, thanks for the feedback.  
![image](https://user-images.githubusercontent.com/44851962/123155934-b1213c80-d436-11eb-9b08-eae77a0e901b.png)
Here is how it looks like currently on desktop.

2021-06-25 00:40 UTC, nyxordinal commented
![image](https://user-images.githubusercontent.com/85892079/123351964-834c0d00-d588-11eb-9dc2-20e1cfeb775c.png)
Is it supposed to be like this? or the two columns should be in the center of the screen?

2021-06-25 00:53 UTC, nyxordinal commented
Also when I try to build the frontend an error still pops up
![image](https://user-images.githubusercontent.com/85892079/123352823-57318b80-d58a-11eb-8bb8-a8f9541fe527.png)

2021-06-25 16:20 UTC, Austinx88 commented
Fixed the current issues however found out that it doesn't look as wanted with empty space on text and on mobile doesn't look proper as well so working on that

2021-06-26 01:56 UTC, Austinx88 commented
Finished the message card page, hopefully last commit. 
![image](https://user-images.githubusercontent.com/44851962/123498711-b1206880-d5ff-11eb-93b9-0406adb661b4.png)
Something to note is that react stack grid needs to be install in order to run, not sure if something does it automatically once the package.json file is changed.

2021-06-26 13:12 UTC, nyxordinal commented on package.json
>      "typescript": "^4.3.2"
``
```suggestion
    "typescript": "^4.3.2",
    "react-stack-grid": "^0.7.1"
```

2021-06-26 13:12 UTC, nyxordinal commented on package.json
>      "typescript": "^4.3.2"
minor typo in package.json

2021-06-26 13:18 UTC, nyxordinal commented
![image](https://user-images.githubusercontent.com/85892079/123514137-8a276c80-d6bb-11eb-85fd-e593d3439459.png)
I'm sorry, this what it looks like when I try to run it in my local machine, do I have a miss somewhere?

2021-06-26 21:02 UTC, azuraga commented
I have the same inconsistency with card spacing. Also, isn't it better to just have an array of card data, instead of an array of *JSONs* containing card data?

2021-06-26 21:09 UTC, azuraga commented
> I have the same inconsistency with card spacing. Also, isn't it better to just have an array of card data, instead of an array of _JSONs_ containing card data?

Update on the spacing: it seems to happen upon first fresh load of the page, and gets resolved upon reload.

2021-06-26 21:21 UTC, azuraga requested changes
I suggested a thing about the `font-size` unit. Also, the fonts don't have a `serif`, `sans-serif`, etc. attached, which, together with the `font-size` thing, might have caused some undefined behaviour.

2021-06-26 21:21 UTC, azuraga commented on packages/frontend/components/MessageCards/MessageCard.module.scss
> +    font-size: 24;
Missing unit. I think you mean `px`, but that seems to be a bit too big compared to what you had before. `16px` works fine.

2021-06-26 21:52 UTC, azuraga commented
Since the spacing issue has to do with animation, the optimized production build might automatically resolve it.

2021-06-27 00:41 UTC, Austinx88 commented
> I suggested a thing about the `font-size` unit. Also, the fonts don't have a `serif`, `sans-serif`, etc. attached, which, together with the `font-size` thing, might have caused some undefined behavior.
> 
> Also, isn't it better to just have an array of card data, instead of an array of _JSONs_ containing card data?

Now that I think of it, it does make more sense to do instead. First I thought I needed a key thing with id to work but looking back it does nothing, will change it.

2021-06-27 18:42 UTC, azuraga reviewed
> Now that I think of it, it does make more sense to do instead. First I thought I needed a key thing with id to work but looking back it does nothing, will change it.

How's progress on this?

2021-06-27 18:42 UTC, azuraga commented on package.json
> +    "react-stack-grid": "^0.7.1",
```suggestion

```

2021-06-28 01:16 UTC, Austinx88 commented
> > Now that I think of it, it does make more sense to do instead. First I thought I needed a key thing with id to work but looking back it does nothing, will change it.
> 
> How's progress on this?

Just finished it, sorry about being late was busy all day. Free in the next couple of days can work more whenever needed.

2021-06-28 01:31 UTC, azuraga requested changes
> sorry about being late was busy all day

No worries! I have one small change request, and then I think it's ready to be merged.

2021-06-28 01:31 UTC, azuraga commented on packages/frontend/pages/messages/index.tsx
> +      <MessageList key={'1'} cardData={Messages} />
Key isn't necessary in this case.
```suggestion
      <MessageList cardData={Messages} />
```

2021-06-29 05:27 UTC, nyxordinal commented
Hi! It seems that the gap bug still exists when the page is first loaded, maybe you want to consider using `masonry-board` as in #73 ?

2021-06-29 16:51 UTC, Austinx88 commented
Will do, I'll get working on that

2021-06-29 18:19 UTC, Austinx88 commented
Messages page works now and looks like this 
![image](https://user-images.githubusercontent.com/44851962/123847760-f46f2580-d8e4-11eb-8329-cbf14b0fbeb8.png)

2021-06-29 19:53 UTC, azuraga commented
Doesn't work properly on mobile
![image](https://user-images.githubusercontent.com/73472335/123858996-6c107500-d924-11eb-9947-e6b3f9c49c16.png)

2021-06-29 19:58 UTC, azuraga commented
> Doesn't work properly on mobile. I'm looking for a fix
> ![image](https://user-images.githubusercontent.com/73472335/123858996-6c107500-d924-11eb-9947-e6b3f9c49c16.png)

update: fix lays in modifying `styles.container`

2021-06-29 21:34 UTC, azuraga commented
It might be better to inherit the Fanart MasonryBoard instead of creating a new one that barely has any difference. With that we can also easily fix bugs like this.

2021-06-29 21:44 UTC, Austinx88 commented
Will do, at first thought it was better to make it two separate things to make it easier to make small changes.

2021-06-29 21:47 UTC, azuraga commented
> Will do, at first thought it was better to make it two separate things to make it easier to make small changes.

Indeed, but since the two are pretty much the same concept, we could add those modifications in a different manner. I've incorporated using the fanart board for messages, too, will suggest the code in a minute.

2021-06-29 21:50 UTC, azuraga requested changes
Fix for the message card misalignment. Will use 3 messages per row, can be adjusted once `MasonryBoard` is properly implemented. This will be done in a future PR.

2021-06-29 21:50 UTC, azuraga commented on packages/frontend/components/MessageCards/MessageList.tsx
> +}
```suggestion
import React from 'react'
import MessageCard from './MessageCard'
import MessageProps from '../../interfaces/messageProps'
import styles from '../Fanart/styles.module.scss'
import MasonryBoard from '../MasonryBoard'

export default function MessageList(props: MessageProps) {
  const cards = props.cardData.map((message, i) => (
    <MessageCard key={i} {...message} />
  ))
  return (
    <div className={styles.fanart_board}>
      <MasonryBoard> {cards}</MasonryBoard>
    </div>
  )
}
```

2021-06-29 22:20 UTC, azuraga commented
Alright one small thing. The one difference between fanart and messages in that board seems to be the breakpoints, so can you add a `breakpointCols` parameter to `MasonryBoard` and have `FanartBoard` and `MessageBoard` use appropriate parameters? For `FanartBoard` you can copy the `breakpointColsObj` from `MasonryBoard`, for `MessageBoard` the following seems to work:

```js
const breakpointColumnsObj = {
  default: 3,
  1160: 2,
  860: 1,
}
```

Also, the unused MasonryBoard stuff in the MessageCard can be removed.

2021-06-29 22:30 UTC, Austinx88 commented
Sure shouldn't take too long

2021-06-30 01:44 UTC, azuraga approved these changes

2021-06-30 12:04 UTC, nyxordinal commented
Please try to merge the latest commit from main branch again into this PR

2021-06-30 14:30 UTC, merged