Implement create message API in message form
Kaichou-Project/kaichou-graduation pull request #49
Opened 2021-06-19 15:23 UTC by yovic4

I tried to do implement create message API for the message form.

Few things to note:
- I add axios for making the request
- I change the .env format for server_url so that it can be used at browser side too

2021-06-21 09:04 UTC, RedMaps requested changes

2021-06-21 09:04 UTC, RedMaps commented on packages/frontend/interfaces/message.ts
> +  // avatar_url: string
This has been removed since we wont be using it

2021-06-21 09:04 UTC, RedMaps commented on packages/frontend/.env.example
> +NEXT_PUBLIC_SERVER_URL="http://localhost:5000/public/v1"
I'd call this API_URL or something for clarity and shortness

2021-06-21 09:04 UTC, RedMaps commented on packages/frontend/api/message.ts
> +  await messageInstance.post('', data)
I think you should move the specific path to the specific function.
```suggestion
  baseURL: process.env.NEXT_PUBLIC_SERVER_URL,
})

export async function createMessage(data: MessageInterface) {
  await messageInstance.post('/message', data)
```

2021-06-21 09:04 UTC, RedMaps commented on packages/frontend/components/Forms/FormMessage.tsx
> +    // data.avatar_url = data.avatar_url.trim()
This has been removed since we wont be using it.

2021-06-21 10:35 UTC, yovic4 commented on packages/frontend/interfaces/message.ts
> +  // avatar_url: string
So, I can remove the input from the message form too right?

2021-06-21 10:46 UTC, yovic4 commented on packages/frontend/.env.example
> +NEXT_PUBLIC_SERVER_URL="http://localhost:5000/public/v1"
ok changing it to `NEXT_PUBLIC_API_URL`

2021-06-21 10:53 UTC, yovic4 commented on packages/frontend/interfaces/message.ts
> +  // avatar_url: string
![image](https://user-images.githubusercontent.com/85892325/122751119-8cec2100-d2b9-11eb-8f81-290eebef38c8.png)
Done, the form become like this

2021-06-21 10:53 UTC, yovic4 commented on packages/frontend/.env.example
> +NEXT_PUBLIC_SERVER_URL="http://localhost:5000/public/v1"
done

2021-06-21 10:54 UTC, yovic4 commented on packages/frontend/components/Forms/FormMessage.tsx
> +    // data.avatar_url = data.avatar_url.trim()
done

2021-06-21 19:17 UTC, azuraga approved these changes

2021-06-23 02:56 UTC, RedMaps approved these changes
Sorry for taking so long!

2021-06-23 02:56 UTC, merged