Create credits layout
Kaichou-Project/kaichou-graduation pull request #85
Opened 2021-06-30 04:12 UTC by keijeizei

2021-07-01 09:23 UTC, RedMaps requested changes
Job well done, some minor issues and I'd advocate for giving the credits page a big padding on the left and right so the text is easier to read and the visuals are improved, maybe around this much:
<img width="1888" alt="Screenshot 2021-07-01 at 11 21 50" src="https://user-images.githubusercontent.com/16868419/124100310-aa11b400-da5e-11eb-975c-7d1d05054805.png">

2021-07-01 09:23 UTC, RedMaps commented on packages/frontend/components/Navigation/Navigation.tsx
> +      {mode != Mode.FORM && (
```suggestion
      {mode !== Mode.FORM && (
```

2021-07-01 09:23 UTC, RedMaps commented on packages/frontend/pages/credits/index.tsx
> +        innovate the world of vtubers and paving the way for HoloEN. We grateful
```suggestion
        innovate the world of vtubers and paving the way for HoloEN. We&apos;re grateful
```

2021-07-02 02:24 UTC, nyxordinal commented
The page is already good, one comment if I may, could you increase the font size? 
I think it's a bit difficult for eyes to read the text in current font size

2021-07-02 05:22 UTC, nyxordinal approved these changes
Nice work !

2021-07-02 13:12 UTC, RedMaps approved these changes
Looks good now!

2021-07-02 13:12 UTC, merged